apiVersion: grizzly.grafana.com/v1alpha1
kind: Dashboard
metadata:
  folder: linuxfabrik-monitoring-plugins
  name: apache-solr-version
spec:
  schemaVersion: 2023041201
  tags:
    - Linuxfabrik
    - Grizzly
    - static
  time:
    from: now-90d
    to: now
  timepicker:
    hidden: false
    refresh_intervals:
    - 1m
  timezone: browser
  title: Apache Solr Version
  uid: linuxfabrik-monitoring-plugins-apache-solr-version
  editable: true
  liveNow: true
  refresh: 1m
  templating:
    list:
    - hide: 2
      label: Command
      name: command
      query: cmd-check-apache-solr-version
      type: constant
    - label: Hostname
      name: hostname
      query: SHOW TAG VALUES FROM "cmd-check-apache-solr-version" WITH KEY = "hostname"
      refresh: 1
      sort: 1
      type: query
    - label: Service
      name: service
      query: SHOW TAG VALUES FROM "cmd-check-apache-solr-version" WITH KEY = "service" WHERE hostname = '$hostname'
      refresh: 1
      sort: 1
      type: query

  panels:

  - title: Apache Solr Version
    type: timeseries
    gridPos:
      h: 8
      w: 12
      x: 0
      y: 0
    fieldConfig:
      defaults:
        color:
          mode: palette-classic
        custom:
          lineInterpolation: smooth
          showPoints: always
          spanNulls: true
        decimals: 3
        unit: none
    options:
      legend:
        calcs:
        - min
        - max
        displayMode: table
        placement: bottom
        showLegend: true
      tooltip:
        mode: multi
        sort: none

    targets:

    - alias: apache-solr-version
      refId: apache-solr-version
      groupBy:
      - params:
        - $interval
        type: time
      measurement: /^$command$/
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '=~'
        value: /^$hostname$/
      - condition: AND
        key: service
        operator: '='
        value: $service
      - condition: AND
        key: metric
        operator: '='
        value: apache-solr-version
