---
variants:
  - linux
  - windows

overwrites:
  '["ServiceTemplate"]["tpl-service-composer-version"]["check_interval"]': 86400
  '["ServiceTemplate"]["tpl-service-composer-version"]["enable_perfdata"]': true
  '["ServiceTemplate"]["tpl-service-composer-version"]["retry_interval"]': 60
